apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp-chart.fullname" . }}
data:
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  FEATURE_X_ENABLED: {{ .Values.config.FEATURE_X_ENABLED | quote }}
